Auth
DevKleber/cashmanager-app pull request #11
Opened 2021-05-14 01:12 UTC by thyerre

2021-05-14 01:13 UTC, thyerre commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ver despesas por mes](https://trello.com/c/tnM5gwN7/39-ver-despesas-por-mes)

2021-05-14 01:34 UTC, thyerre commented
![](https://github.trello.services/images/mini-trello-icon.png) [Planned expenses](https://trello.com/c/yVLY0Ayh/36-planned-expenses)

2021-05-14 18:47 UTC, DevKleber requested changes

2021-05-14 18:47 UTC, DevKleber commented on src/pages/CreditCard/CreditCardDetail/index.tsx
> +    async function setMonthCurrent() {
```suggestion
    async function setCurrentMonth() {
```

2021-05-14 18:47 UTC, DevKleber commented on src/pages/CreditCard/CreditCardDetail/index.tsx
> +        const d = new Date();
```suggestion
        const date= new Date();
```

2021-05-14 18:47 UTC, DevKleber commented on src/pages/CreditCard/CreditCardDetail/index.tsx
> +                <IconText name="arrow-left" size={18} color='#666666'onPress={() => {alterMonth(month > 0 ? month - 1 : 0).then(() => getCreditCard())}} />
coloca o then na funcao altermonth

2021-05-16 13:44 UTC, DevKleber approved these changes

2021-05-16 13:44 UTC, merged